package com.helium.core.wallet.domain;

public enum WalletAuditEventType {
    ASSET_REGISTERED,
    NETWORK_REGISTERED,
    DEPOSIT_ADDRESS_ASSIGNED,
    DEPOSIT_DETECTED,
    DEPOSIT_CONFIRMATIONS_UPDATED,
    DEPOSIT_POSTED,
    WITHDRAWAL_REQUESTED,
    WITHDRAWAL_APPROVED,
    WITHDRAWAL_REJECTED,
    WITHDRAWAL_BROADCAST_RECORDED,
    WITHDRAWAL_CONFIRMED,
    CHAIN_MONITOR_UPDATED,
    RECONCILIATION_CHECKED
}

