package com.helium.core.wallet.domain;

public enum WithdrawalQueueStatus {
    REQUESTED,
    VALIDATING,
    APPROVED,
    WAITING_SIGN,
    BUILDING_TRANSACTION,
    TRANSACTION_BUILT,
    BUILD_FAILED,
    WAITING_SIGNER,
    SIGNING,
    SIGNED,
    SIGN_FAILED,
    WAITING_BROADCAST,
    BROADCASTING,
    BROADCAST_FAILED,
    BROADCASTED,
    PENDING_CONFIRMATIONS,
    CONFIRMING,
    CONFIRMATION_FAILED,
    REORG_DETECTED,
    CONFIRMED,
    FAILED,
    CANCELLED
}
