package com.helium.core.authuser.domain;

public enum Permission {
    VIEW_FINANCE_DASHBOARDS,
    INITIATE_COLD_SWEEP,
    APPROVE_COLD_SWEEP,
    INITIATE_ACCOUNT_FREEZE,
    APPROVE_ACCOUNT_FREEZE,
    VIEW_AUDIT_LOGS,
    GENERATE_REGULATORY_REPORTS,
    MANAGE_SECURITY_POLICIES
}
