package com.helium.core.authuser.domain;

public enum SecurityAuditEventType {
    USER_REGISTERED,
    EMAIL_VERIFICATION_ISSUED,
    EMAIL_VERIFIED,
    LOGIN_SUCCEEDED,
    LOGIN_FAILED,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    ACCOUNT_SUSPENDED,
    ACCOUNT_REACTIVATED,
    LOGOUT,
    SESSION_REVOKED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    PASSWORD_CHANGED,
    ROLE_GRANTED,
    ROLE_REVOKED
}
