export const queryKeys = {
  session: ["session"] as const,
  authSessions: ["auth", "sessions"] as const,
  balances: ["wallet", "balances"] as const,
  depositAddresses: ["wallet", "deposit-addresses"] as const,
  deposits: ["wallet", "deposits"] as const,
  withdrawals: ["wallet", "withdrawals"] as const,
  dashboard: ["dashboard"] as const,
  dashboardPortfolio: ["dashboard", "portfolio"] as const,
  dashboardMarkets: ["dashboard", "markets"] as const,
  dashboardActivity: ["dashboard", "activity"] as const,
  watchlist: ["dashboard", "watchlist"] as const,
  notifications: ["notifications"] as const,
  notificationUnreadCount: ["notifications", "unread-count"] as const,
  priceAlerts: ["price-alerts"] as const,
  preferences: ["preferences"] as const,
  markets: ["markets"] as const,
  market: (symbol: string) => ["market-data", "market", symbol] as const,
  ticker: (symbol: string) => ["market-data", "ticker", symbol] as const,
  marketStats: (symbol: string) => ["market-data", "stats", symbol] as const,
  marketStreamStatus: ["market-data", "status"] as const,
  orderBook: (symbol: string) => ["market-data", "book", symbol] as const,
  publicTrades: (symbol: string) => ["market-data", "trades", symbol] as const,
  candles: (symbol: string, interval = "1m") => ["market-data", "candles", symbol, interval] as const,
  orderPreview: (symbol: string, side: string, type: string, quantity: string, price: string) => ["trading", "orders", "preview", symbol, side, type, quantity, price] as const,
  order: (orderId: string) => ["trading", "orders", orderId] as const,
  openOrders: ["trading", "orders", "open"] as const,
  orderHistory: ["trading", "orders", "history"] as const,
  trades: ["trading", "trades"] as const,
  adminUsers: ["admin", "users"] as const,
  adminAudit: ["admin", "audit"] as const,
  adminMarketControls: ["admin", "markets"] as const,
  adminPendingWithdrawals: ["admin", "withdrawals", "pending"] as const,
  reconciliationReports: ["admin", "reconciliation", "reports"] as const,
  reconciliationDiscrepancies: ["admin", "reconciliation", "discrepancies"] as const
};
