export const queryKeys = {
  session: ["session"] as const,
  balances: ["wallet", "balances"] as const,
  depositAddresses: ["wallet", "deposit-addresses"] as const,
  deposits: ["wallet", "deposits"] as const,
  withdrawals: ["wallet", "withdrawals"] as const,
  markets: ["markets"] as const,
  ticker: (symbol: string) => ["market-data", "ticker", symbol] as const,
  orderBook: (symbol: string) => ["market-data", "book", symbol] as const,
  publicTrades: (symbol: string) => ["market-data", "trades", symbol] as const,
  candles: (symbol: string) => ["market-data", "candles", symbol] as const,
  openOrders: ["trading", "orders", "open"] as const,
  orderHistory: ["trading", "orders", "history"] as const,
  trades: ["trading", "trades"] as const,
  adminUsers: ["admin", "users"] as const,
  adminAudit: ["admin", "audit"] as const,
  adminMarketControls: ["admin", "markets"] as const,
  adminPendingWithdrawals: ["admin", "withdrawals", "pending"] as const,
  reconciliationReports: ["admin", "reconciliation", "reports"] as const,
  reconciliationDiscrepancies: ["admin", "reconciliation", "discrepancies"] as const
};
