import { PageHeader } from "@/components/layout/app-shell";
import { ProtectedShell } from "@/components/layout/protected-shell";
import { DepositAddresses, DepositHistory } from "@/features/wallet/components/wallet-panels";

export default function DepositPage() {
  return (
    <ProtectedShell>
      <PageHeader title="Deposit" detail="Use only addresses generated by the Wallet module for the selected asset and network." />
      <div className="space-y-6">
        <DepositAddresses />
        <DepositHistory />
      </div>
    </ProtectedShell>
  );
}
