plugins {
    id("org.springframework.boot")
    id("io.spring.dependency-management")
}

dependencies {
    implementation(project(":modules:auth-user"))
    implementation(project(":modules:compliance-lite"))
    implementation(project(":modules:wallet"))
    implementation(project(":modules:ledger"))
    implementation(project(":modules:trading"))
    implementation(project(":modules:matching"))
    implementation(project(":modules:market-data"))
    implementation(project(":modules:admin"))
    implementation(project(":modules:audit"))
    implementation(project(":modules:outbox"))

    implementation(project(":shared:common"))
    implementation(project(":shared:security"))
    implementation(project(":shared:persistence"))
    implementation(project(":shared:observability"))

    implementation("org.springframework.vault:spring-vault-core:3.1.1")
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-starter-data-redis")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    implementation("org.springframework.boot:spring-boot-starter-validation")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-security")
    implementation("org.springframework.boot:spring-boot-starter-websocket")
    implementation("io.micrometer:micrometer-registry-prometheus")
    implementation("io.micrometer:micrometer-tracing-bridge-otel")
    implementation("io.opentelemetry:opentelemetry-exporter-otlp")
    implementation("io.opentelemetry:opentelemetry-sdk")
    implementation("io.opentelemetry:opentelemetry-api")
    implementation("org.springframework.security:spring-security-core")
    implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.14")
    implementation("net.logstash.logback:logstash-logback-encoder:8.0")
    implementation("org.flywaydb:flyway-core")
    implementation("org.flywaydb:flyway-database-postgresql")

    runtimeOnly("org.postgresql:postgresql")

    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("org.springframework.security:spring-security-core")
    testImplementation("org.testcontainers:junit-jupiter")
    testImplementation("org.testcontainers:postgresql")
    testImplementation("org.testcontainers:testcontainers")
    testImplementation(project(":shared:test-support"))
}
