package com.helium.core.admin.domain;

public enum AdminAuditAction {
    USER_STATUS_CHANGED,
    ROLE_GRANTED,
    ROLE_REVOKED,
    WITHDRAWAL_APPROVED,
    WITHDRAWAL_REJECTED,
    MARKET_UPDATED,
    FEE_SCHEDULE_UPDATED,
    TRADING_HALTED,
    TRADING_RESUMED,
    RECONCILIATION_REPORT_CREATED,
    MANUAL_RECONCILIATION_OPENED,
    MANUAL_RECONCILIATION_RESOLVED,
    CSV_EXPORTED
}
