spring:
  config:
    activate:
      on-profile: production
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

management:
  endpoint:
    health:
      show-details: never
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${HELIUM_OTLP_ENDPOINT:http://otel-collector:4318/v1/traces}

helium:
  environment: production
